/**
 * Centralized game configuration constants
 * Update here to change game behavior globally
 */

export const GAME_CONSTANTS = {
	// Multiplayer Game
	MULTIPLAYER_ROUND_TIME_SECONDS: 8,
	MULTIPLAYER_WORDS_PER_GAME: 10,
	MULTIPLAYER_ROUND_END_DELAY_MS: 7000,
	MULTIPLAYER_SPEED_BONUS_DIVISOR: 80,
	MULTIPLAYER_BASE_POINTS: 100,
	MULTIPLAYER_ROOM_TIMEOUT_MS: 30 * 60 * 1000, // 30 minutes

	// Solo Game
	SOLO_INITIAL_TIME_SECONDS: 60,
	SOLO_TIME_BONUS_CORRECT: 2,
	SOLO_TIME_PENALTY_WRONG: 5,
	SOLO_POINTS_CORRECT: 100,
	SOLO_POINTS_BOTH: 150,

	// Leaderboard
	LEADERBOARD_LIMIT: 10,

	// Room codes
	ROOM_CODE_LENGTH: 6,
	ROOM_CODE_CHARSET: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
} as const;

export type GameConstants = typeof GAME_CONSTANTS;
